### ISSUE TITLE
Reduce async calls

### ISSUE THREAD

**Issue by andrew264** [Wrenchi404/Wrenchi#2]
https://github.com/Wrenchi404/Wrenchi/blob/e24aac49553b04372cf40c9f6d5fe1b733db625c/src/utils/convert.ts#L3
https://github.com/Wrenchi404/Wrenchi/blob/e24aac49553b04372cf40c9f6d5fe1b733db625c/src/utils/convert.ts#L14

Bruh you can make a single function to do this like
convertToHumanFormat(x){
// convert your num here
}

pass your view or like count alone to your function instead of fetching multiple times with ytdl

**Comment by Wrenchi404** [comment]
I used async in that because ytdl need to be awaited. Check the below code in that file so you can understand it.

**Comment by andrew264** [comment]
what i am trying to say is make a fn to convert int -> 1M so you can remove ytdl and async
and you need only one function for both likes and views

**Comment by Wrenchi404** [comment]
well that's an idea you got there
let me try it out
